# Generated by Django 4.2.6 on 2024-04-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_useraddress_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userotp',
            name='user',
        ),
        migrations.AddField(
            model_name='userotp',
            name='mobile',
            field=models.CharField(max_length=15, verbose_name='Mobile'),
            preserve_default=False,
        ),
    ]
