# Generated by Django 4.2.6 on 2024-04-14 00:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userotp_user_userotp_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='action',
            field=models.CharField(default='auth', max_length=24, verbose_name='Action'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userotp',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Expires At'),
            preserve_default=False,
        ),
    ]
