# Generated by Django 4.2.6 on 2024-04-16 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0001_initial'),
        ('users', '0008_alter_useraddress_address_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='lookups.city', verbose_name='City'),
        ),
    ]
