# Generated by Django 4.2.6 on 2024-04-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_useraddress_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='mobile',
            field=models.CharField(max_length=30, verbose_name='Mobile'),
        ),
    ]
