# Generated by Django 4.2.6 on 2024-04-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_userotp_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='action',
            field=models.CharField(max_length=128, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='mobile',
            field=models.CharField(max_length=15, verbose_name='Mobile'),
        ),
    ]
