# Generated by Django 4.2.6 on 2024-05-18 17:44
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=256, verbose_name='Name (EN)')),
                ('name_ar', models.CharField(max_length=256, verbose_name='Name (AR)')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/icons/', verbose_name='Icon')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', to='services.category', verbose_name='Main Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=256, verbose_name='Name (EN)')),
                ('name_ar', models.CharField(max_length=256, verbose_name='Name (AR)')),
                ('description_en', models.TextField(verbose_name='Description (EN)')),
                ('description_ar', models.TextField(verbose_name='Description (AR)')),
                ('tag_en', models.CharField(blank=True, max_length=256, null=True, verbose_name='Tag (EN)')),
                ('tag_ar', models.CharField(blank=True, max_length=256, null=True, verbose_name='Tag (AR)')),
                ('warranty', models.IntegerField(blank=True, help_text='In months', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Warranty')),
                ('show_warranty', models.BooleanField(default=False, verbose_name='Show Warranty')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/icons/', verbose_name='Icon')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/images/', verbose_name='Image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal(0.00))], verbose_name='Price')),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal(0.00))], verbose_name='Offer Price')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Main Category',
                'verbose_name_plural': 'Main Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('services.category',),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('services.category',),
        ),
    ]
